import { CityInfo } from '../types';

export const POPULAR_CITIES: CityInfo[] = [
  // Egypt (مصر)
  {
    id: 'cairo-eg',
    nameAr: 'القاهرة',
    nameEn: 'Cairo',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 30.0444,
    lng: 31.2357,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'alex-eg',
    nameAr: 'الإسكندرية',
    nameEn: 'Alexandria',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 31.2001,
    lng: 29.9187,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'giza-eg',
    nameAr: 'الجيزة',
    nameEn: 'Giza',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 30.0131,
    lng: 31.2089,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'mansoura-eg',
    nameAr: 'المنصورة',
    nameEn: 'Mansoura',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 31.0409,
    lng: 31.3785,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'aswan-eg',
    nameAr: 'أسوان',
    nameEn: 'Aswan',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 24.0889,
    lng: 32.8998,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'luxor-eg',
    nameAr: 'الأقصر',
    nameEn: 'Luxor',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 25.6872,
    lng: 32.6396,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'tanta-eg',
    nameAr: 'طنطا',
    nameEn: 'Tanta',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 30.7865,
    lng: 31.0004,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },
  {
    id: 'port-said-eg',
    nameAr: 'بورسعيد',
    nameEn: 'Port Said',
    countryAr: 'مصر',
    countryEn: 'Egypt',
    countryCode: 'EG',
    lat: 31.2653,
    lng: 32.3019,
    timezone: 'Africa/Cairo',
    recommendedMethod: 'Egyptian',
  },

  // Saudi Arabia (السعودية)
  {
    id: 'makkah-sa',
    nameAr: 'مكة المكرمة',
    nameEn: 'Makkah',
    countryAr: 'المملكة العربية السعودية',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 21.4225,
    lng: 39.8262,
    timezone: 'Asia/Riyadh',
    recommendedMethod: 'UmmAlQura',
  },
  {
    id: 'madinah-sa',
    nameAr: 'المدينة المنورة',
    nameEn: 'Madinah',
    countryAr: 'المملكة العربية السعودية',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.5247,
    lng: 39.5692,
    timezone: 'Asia/Riyadh',
    recommendedMethod: 'UmmAlQura',
  },
  {
    id: 'riyadh-sa',
    nameAr: 'الرياض',
    nameEn: 'Riyadh',
    countryAr: 'المملكة العربية السعودية',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lng: 46.6753,
    timezone: 'Asia/Riyadh',
    recommendedMethod: 'UmmAlQura',
  },
  {
    id: 'jeddah-sa',
    nameAr: 'جدة',
    nameEn: 'Jeddah',
    countryAr: 'المملكة العربية السعودية',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 21.5433,
    lng: 39.1728,
    timezone: 'Asia/Riyadh',
    recommendedMethod: 'UmmAlQura',
  },
  {
    id: 'dammam-sa',
    nameAr: 'الدمام',
    nameEn: 'Dammam',
    countryAr: 'المملكة العربية السعودية',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 26.4207,
    lng: 50.0888,
    timezone: 'Asia/Riyadh',
    recommendedMethod: 'UmmAlQura',
  },

  // UAE (الإمارات)
  {
    id: 'dubai-ae',
    nameAr: 'دبي',
    nameEn: 'Dubai',
    countryAr: 'الإمارات العربية المتحدة',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 25.2048,
    lng: 55.2708,
    timezone: 'Asia/Dubai',
    recommendedMethod: 'Dubai',
  },
  {
    id: 'abu-dhabi-ae',
    nameAr: 'أبوظبي',
    nameEn: 'Abu Dhabi',
    countryAr: 'الإمارات العربية المتحدة',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 24.4539,
    lng: 54.3773,
    timezone: 'Asia/Dubai',
    recommendedMethod: 'Dubai',
  },
  {
    id: 'sharjah-ae',
    nameAr: 'الشارقة',
    nameEn: 'Sharjah',
    countryAr: 'الإمارات العربية المتحدة',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 25.3463,
    lng: 55.4209,
    timezone: 'Asia/Dubai',
    recommendedMethod: 'Dubai',
  },

  // Kuwait (الكويت)
  {
    id: 'kuwait-kw',
    nameAr: 'مدينة الكويت',
    nameEn: 'Kuwait City',
    countryAr: 'الكويت',
    countryEn: 'Kuwait',
    countryCode: 'KW',
    lat: 29.3759,
    lng: 47.9774,
    timezone: 'Asia/Kuwait',
    recommendedMethod: 'Kuwait',
  },

  // Qatar (قطر)
  {
    id: 'doha-qa',
    nameAr: 'الدوحة',
    nameEn: 'Doha',
    countryAr: 'قطر',
    countryEn: 'Qatar',
    countryCode: 'QA',
    lat: 25.2854,
    lng: 51.5310,
    timezone: 'Asia/Qatar',
    recommendedMethod: 'Qatar',
  },

  // Palestine (فلسطين)
  {
    id: 'jerusalem-ps',
    nameAr: 'القدس الشريف',
    nameEn: 'Jerusalem',
    countryAr: 'فلسطين',
    countryEn: 'Palestine',
    countryCode: 'PS',
    lat: 31.7683,
    lng: 35.2137,
    timezone: 'Asia/Jerusalem',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'gaza-ps',
    nameAr: 'غزة',
    nameEn: 'Gaza',
    countryAr: 'فلسطين',
    countryEn: 'Palestine',
    countryCode: 'PS',
    lat: 31.5017,
    lng: 34.4668,
    timezone: 'Asia/Gaza',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Jordan (الأردن)
  {
    id: 'amman-jo',
    nameAr: 'عمّان',
    nameEn: 'Amman',
    countryAr: 'الأردن',
    countryEn: 'Jordan',
    countryCode: 'JO',
    lat: 31.9454,
    lng: 35.9284,
    timezone: 'Asia/Amman',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Syria (سوريا)
  {
    id: 'damascus-sy',
    nameAr: 'دمشق',
    nameEn: 'Damascus',
    countryAr: 'سوريا',
    countryEn: 'Syria',
    countryCode: 'SY',
    lat: 33.5138,
    lng: 36.2765,
    timezone: 'Asia/Damascus',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Iraq (العراق)
  {
    id: 'baghdad-iq',
    nameAr: 'بغداد',
    nameEn: 'Baghdad',
    countryAr: 'العراق',
    countryEn: 'Iraq',
    countryCode: 'IQ',
    lat: 33.3152,
    lng: 44.3661,
    timezone: 'Asia/Baghdad',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'erbil-iq',
    nameAr: 'أربيل',
    nameEn: 'Erbil',
    countryAr: 'العراق',
    countryEn: 'Iraq',
    countryCode: 'IQ',
    lat: 36.1901,
    lng: 44.0091,
    timezone: 'Asia/Baghdad',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Morocco (المغرب)
  {
    id: 'rabat-ma',
    nameAr: 'الرباط',
    nameEn: 'Rabat',
    countryAr: 'المغرب',
    countryEn: 'Morocco',
    countryCode: 'MA',
    lat: 34.0209,
    lng: -6.8416,
    timezone: 'Africa/Casablanca',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'casablanca-ma',
    nameAr: 'الدار البيضاء',
    nameEn: 'Casablanca',
    countryAr: 'المغرب',
    countryEn: 'Morocco',
    countryCode: 'MA',
    lat: 33.5731,
    lng: -7.5898,
    timezone: 'Africa/Casablanca',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Algeria (الجزائر)
  {
    id: 'algiers-dz',
    nameAr: 'الجزائر العاصمة',
    nameEn: 'Algiers',
    countryAr: 'الجزائر',
    countryEn: 'Algeria',
    countryCode: 'DZ',
    lat: 36.7538,
    lng: 3.0588,
    timezone: 'Africa/Algiers',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Tunisia (تونس)
  {
    id: 'tunis-tn',
    nameAr: 'تونس',
    nameEn: 'Tunis',
    countryAr: 'تونس',
    countryEn: 'Tunisia',
    countryCode: 'TN',
    lat: 36.8065,
    lng: 10.1815,
    timezone: 'Africa/Tunis',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Sudan (السودان)
  {
    id: 'khartoum-sd',
    nameAr: 'الخرطوم',
    nameEn: 'Khartoum',
    countryAr: 'السودان',
    countryEn: 'Sudan',
    countryCode: 'SD',
    lat: 15.5007,
    lng: 32.5599,
    timezone: 'Africa/Khartoum',
    recommendedMethod: 'Egyptian',
  },

  // Yemen (اليمن)
  {
    id: 'sanaa-ye',
    nameAr: 'صنعاء',
    nameEn: 'Sanaa',
    countryAr: 'اليمن',
    countryEn: 'Yemen',
    countryCode: 'YE',
    lat: 15.3694,
    lng: 44.1910,
    timezone: 'Asia/Aden',
    recommendedMethod: 'UmmAlQura',
  },

  // Oman (عمان)
  {
    id: 'muscat-om',
    nameAr: 'مسقط',
    nameEn: 'Muscat',
    countryAr: 'سلطنة عمان',
    countryEn: 'Oman',
    countryCode: 'OM',
    lat: 23.5880,
    lng: 58.3829,
    timezone: 'Asia/Muscat',
    recommendedMethod: 'UmmAlQura',
  },

  // Bahrain (البحرين)
  {
    id: 'manama-bh',
    nameAr: 'المنامة',
    nameEn: 'Manama',
    countryAr: 'البحرين',
    countryEn: 'Bahrain',
    countryCode: 'BH',
    lat: 26.2285,
    lng: 50.5860,
    timezone: 'Asia/Bahrain',
    recommendedMethod: 'UmmAlQura',
  },

  // Lebanon (لبنان)
  {
    id: 'beirut-lb',
    nameAr: 'بيروت',
    nameEn: 'Beirut',
    countryAr: 'لبنان',
    countryEn: 'Lebanon',
    countryCode: 'LB',
    lat: 33.8938,
    lng: 35.5018,
    timezone: 'Asia/Beirut',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Libya (ليبيا)
  {
    id: 'tripoli-ly',
    nameAr: 'طرابلس',
    nameEn: 'Tripoli',
    countryAr: 'ليبيا',
    countryEn: 'Libya',
    countryCode: 'LY',
    lat: 32.8872,
    lng: 13.1913,
    timezone: 'Africa/Tripoli',
    recommendedMethod: 'MuslimWorldLeague',
  },

  // Turkey (تركيا)
  {
    id: 'istanbul-tr',
    nameAr: 'إسطنبول',
    nameEn: 'Istanbul',
    countryAr: 'تركيا',
    countryEn: 'Turkey',
    countryCode: 'TR',
    lat: 41.0082,
    lng: 28.9784,
    timezone: 'Europe/Istanbul',
    recommendedMethod: 'Turkey',
  },
  {
    id: 'ankara-tr',
    nameAr: 'أنقرة',
    nameEn: 'Ankara',
    countryAr: 'تركيا',
    countryEn: 'Turkey',
    countryCode: 'TR',
    lat: 39.9334,
    lng: 32.8597,
    timezone: 'Europe/Istanbul',
    recommendedMethod: 'Turkey',
  },

  // Pakistan (باكستان)
  {
    id: 'karachi-pk',
    nameAr: 'كراتشي',
    nameEn: 'Karachi',
    countryAr: 'باكستان',
    countryEn: 'Pakistan',
    countryCode: 'PK',
    lat: 24.8607,
    lng: 67.0011,
    timezone: 'Asia/Karachi',
    recommendedMethod: 'Karachi',
  },
  {
    id: 'lahore-pk',
    nameAr: 'لاهور',
    nameEn: 'Lahore',
    countryAr: 'باكستان',
    countryEn: 'Pakistan',
    countryCode: 'PK',
    lat: 31.5204,
    lng: 74.3587,
    timezone: 'Asia/Karachi',
    recommendedMethod: 'Karachi',
  },

  // Indonesia & Malaysia
  {
    id: 'jakarta-id',
    nameAr: 'جاكرتا',
    nameEn: 'Jakarta',
    countryAr: 'إندونيسيا',
    countryEn: 'Indonesia',
    countryCode: 'ID',
    lat: -6.2088,
    lng: 106.8456,
    timezone: 'Asia/Jakarta',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'kuala-lumpur-my',
    nameAr: 'كوالالمبور',
    nameEn: 'Kuala Lumpur',
    countryAr: 'ماليزيا',
    countryEn: 'Malaysia',
    countryCode: 'MY',
    lat: 3.1390,
    lng: 101.6869,
    timezone: 'Asia/Kuala_Lumpur',
    recommendedMethod: 'Singapore',
  },

  // Europe & Americas
  {
    id: 'london-gb',
    nameAr: 'لندن',
    nameEn: 'London',
    countryAr: 'المملكة المتحدة',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    timezone: 'Europe/London',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'paris-fr',
    nameAr: 'باريس',
    nameEn: 'Paris',
    countryAr: 'فرنسا',
    countryEn: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    timezone: 'Europe/Paris',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'berlin-de',
    nameAr: 'برلين',
    nameEn: 'Berlin',
    countryAr: 'ألمانيا',
    countryEn: 'Germany',
    countryCode: 'DE',
    lat: 52.5200,
    lng: 13.4050,
    timezone: 'Europe/Berlin',
    recommendedMethod: 'MuslimWorldLeague',
  },
  {
    id: 'new-york-us',
    nameAr: 'نيويورك',
    nameEn: 'New York',
    countryAr: 'الولايات المتحدة',
    countryEn: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lng: -74.0060,
    timezone: 'America/New_York',
    recommendedMethod: 'NorthAmerica',
  },
  {
    id: 'toronto-ca',
    nameAr: 'تورونتو',
    nameEn: 'Toronto',
    countryAr: 'كندا',
    countryEn: 'Canada',
    countryCode: 'CA',
    lat: 43.6532,
    lng: -79.3832,
    timezone: 'America/Toronto',
    recommendedMethod: 'NorthAmerica',
  },
  {
    id: 'sydney-au',
    nameAr: 'سيدني',
    nameEn: 'Sydney',
    countryAr: 'أستراليا',
    countryEn: 'Australia',
    countryCode: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    timezone: 'Australia/Sydney',
    recommendedMethod: 'MuslimWorldLeague',
  },
];

export const CALCULATION_METHODS = [
  {
    key: 'Egyptian',
    nameAr: 'الهيئة المصرية العامة للمساحة',
    nameEn: 'Egyptian General Authority of Survey',
    description: 'الفجر 19.5°، العشاء 17.5° (مصر، أفريقيا، بلاد الشام)',
  },
  {
    key: 'UmmAlQura',
    nameAr: 'جامعة أم القرى - مكة المكرمة',
    nameEn: 'Umm Al-Qura University, Makkah',
    description: 'الفجر 18.5°، العشاء بعد المغرب بـ 90 دقيقة (السعودية والخليج العربي)',
  },
  {
    key: 'MuslimWorldLeague',
    nameAr: 'رابطة العالم الإسلامي',
    nameEn: 'Muslim World League',
    description: 'الفجر 18°، العشاء 17° (أوروبا، الشرق الأقصى، أجزاء من أمريكا)',
  },
  {
    key: 'NorthAmerica',
    nameAr: 'الجمعية الإسلامية لأمريكا الشمالية (ISNA)',
    nameEn: 'Islamic Society of North America',
    description: 'الفجر 15°، العشاء 15° (أمريكا وكندا)',
  },
  {
    key: 'Karachi',
    nameAr: 'جامعة العلوم الإسلامية بكراتشي',
    nameEn: 'University of Islamic Sciences, Karachi',
    description: 'الفجر 18°، العشاء 18° (باكستان، الهند، بنغلاديش، أفغانستان)',
  },
  {
    key: 'Dubai',
    nameAr: 'دائرة الشؤون الإسلامية بدبي',
    nameEn: 'Dubai (UAE)',
    description: 'الفجر 18.2°، العشاء 18.2° (دولة الإمارات العربية المتحدة)',
  },
  {
    key: 'Qatar',
    nameAr: 'وزارة الأوقاف والشؤون الإسلامية بقطر',
    nameEn: 'Qatar',
    description: 'الفجر 18°، العشاء بعد المغرب بـ 90 دقيقة',
  },
  {
    key: 'Kuwait',
    nameAr: 'وزارة الأوقاف والشؤون الإسلامية بالكويت',
    nameEn: 'Kuwait',
    description: 'الفجر 18°، العشاء 17.5°',
  },
  {
    key: 'MoonsightingCommittee',
    nameAr: 'لجنة مراقبة الهلال العالمية',
    nameEn: 'Moonsighting Committee Worldwide',
    description: 'الفجر 18°، العشاء 18° مع تعديلات خطوط العرض',
  },
  {
    key: 'Singapore',
    nameAr: 'المجلس الإسلامي السنغافوري (MUIS)',
    nameEn: 'Singapore (MUIS)',
    description: 'الفجر 20°، العشاء بعد المغرب مع مراعاة زوايا المنطقة الاستوائية',
  },
  {
    key: 'Turkey',
    nameAr: 'رئاسة الشؤون الدينية التركية (ديانت)',
    nameEn: 'Diyanet İşleri Başkanlığı (Turkey)',
    description: 'الفجر 18°، العشاء 17° مع حسابات الشروق والغروب الدقيقة',
  },
  {
    key: 'Tehran',
    nameAr: 'معهد الجيوفيزياء بجامعة طهران',
    nameEn: 'Institute of Geophysics, University of Tehran',
    nameFr: 'Institut de Géophysique, Université de Téhéran',
    description: 'الفجر 17.7°، المغرب 4.5°، العشاء 14°',
  },
  {
    key: 'France',
    nameAr: 'اتحاد المنظمات الإسلامية في فرنسا (UOIF / 12°)',
    nameEn: 'Union of Islamic Organisations of France (12°)',
    nameFr: 'Union des Organisations Islamiques de France (UOIF 12°)',
    description: 'الفجر 12°، العشاء 12° (فرنسا وغرب أوروبا)',
  },
  {
    key: 'Russia',
    nameAr: 'الإدارة الدينية لمسلمي روسيا',
    nameEn: 'Spiritual Administration of Muslims of Russia',
    nameFr: 'Administration Spirituelle des Musulmans de Russie',
    description: 'الفجر 16°، العشاء 15° (روسيا ودول آسيا الوسطى)',
  },
  {
    key: 'JAKIM',
    nameAr: 'مصلحة التقدم الإسلامي الماليزية (JAKIM)',
    nameEn: 'Department of Islamic Development Malaysia (JAKIM)',
    nameFr: 'Département du Développement Islamique de Malaisie (JAKIM)',
    description: 'الفجر 20°، العشاء 18° (ماليزيا وجنوب شرق آسيا)',
  },
];
